"""Initial migration with Project and Segment models

Revision ID: 0c92f587d6d8
Revises:
Create Date: 2025-12-04 21:57:12.558229

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c92f587d6d8"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("source_video", sa.String(length=500), nullable=True),
        sa.Column("extracted_audio", sa.String(length=500), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "segments",
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("start_time", sa.Float(), nullable=False),
        sa.Column("end_time", sa.Float(), nullable=False),
        sa.Column("audio_file", sa.String(length=500), nullable=True),
        sa.Column("original_transcription", sa.Text(), nullable=True),
        sa.Column("translated_text", sa.Text(), nullable=True),
        sa.Column("analysis_json", sa.JSON(), nullable=True),
        sa.Column("tts_voice", sa.String(length=50), nullable=True),
        sa.Column("tts_result_file", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "EXTRACTING",
                "EXTRACTED",
                "ANALYZING",
                "ANALYZED",
                "GENERATING_TTS",
                "COMPLETED",
                "ERROR",
                name="segmentstatus",
            ),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("segments")
    op.drop_table("projects")
    # ### end Alembic commands ###
