"""add project languages and simplify settings

Revision ID: 4d343e2add9e
Revises: bc7764e54841
Create Date: 2025-12-05 03:08:50.213293

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d343e2add9e"
down_revision: Union[str, Sequence[str], None] = "bc7764e54841"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_settings",
        sa.Column(
            "context_description",
            sa.Text(),
            nullable=False,
            server_default="The audio is from outdoor/rural environments, specifically fishing videos.",
        ),
    )
    op.drop_column("app_settings", "analysis_system_prompt")
    op.drop_column("app_settings", "analysis_user_prompt")
    op.add_column(
        "projects",
        sa.Column("source_language", sa.String(length=10), nullable=False, server_default="uk"),
    )
    op.add_column(
        "projects",
        sa.Column("target_language", sa.String(length=10), nullable=False, server_default="en"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "target_language")
    op.drop_column("projects", "source_language")
    op.add_column("app_settings", sa.Column("analysis_user_prompt", sa.TEXT(), nullable=False))
    op.add_column("app_settings", sa.Column("analysis_system_prompt", sa.TEXT(), nullable=False))
    op.drop_column("app_settings", "context_description")
    # ### end Alembic commands ###
