"""add_tts_provider_to_user_settings

Revision ID: ff5ac6cad25d
Revises: fba6c0971288
Create Date: 2025-12-05 10:32:17.462185

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff5ac6cad25d"
down_revision: Union[str, Sequence[str], None] = "fba6c0971288"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_settings",
        sa.Column("tts_provider", sa.String(length=32), nullable=False, server_default="openai"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_settings", "tts_provider")
    # ### end Alembic commands ###
